### ISSUE TITLE
Whats the difference in this an uYou+?

### ISSUE THREAD

**Issue by dhawan1997** [TherionRO/YouTubeiVanced#5]
Sorry, but I thought this was another app. When I open the app, it says uYou version 2.1 need updating. I was a bit confused as the uYou+ app is also separately available.SO what does this do differently? Also, the problem of uYou not being able to download videos exist in this app. Is there a way to fix that?

**Comment by TherionRO** [comment]
Hey.This is a fork of uYou+ based on the latest youtube version,as the official uyou+ maintainers don't have the time to update the app every 2-3 days.I just liked the name and that's why I also renamed the project to ivanced.At this time,ivanced don't have any new tweaks and patches applied compared to uyou+.I am aware of the download failed issue and I will take a closer look to see what's the cause of that.

**Comment by dhawan1997** [comment]
Thank you for your kind response and explanation!

**Comment by TherionRO** [comment]
No problem! If you need any more help you can open another issue.Do note tho that you can find some issues listed on this repo in the readme and also on the official uYou+ wiki,maybe you can find your issue there and fix it as soon as possible.
